# Generated by Django 5.2 on 2025-05-02 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biography')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Location')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('preferred_language', models.CharField(blank=True, max_length=10, verbose_name='Preferred Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
